# This is a basic workflow to help you get started with Actions
name: Slack Notification

# Controls when the action will run. 
on: 
  issues:
    types: [opened, edited]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notification
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: all
          custom_payload: |
            {
              Type: 'Issue',
              Content: `https://github.com/hitendran/universe-automation/issues/${{ env.ISSUE_NUMBER }}`
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
