# This is a basic workflow to help you get started with Actions
name: Slack Notification

# Controls when the action will run. 
on: 
  pull_request:
    types: [opened, edited]
  issues:
    types: [opened, edited]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
#       - run: echo `pull_number=pull_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")` >> $GITHUB_ENV
      - name: Slack Notification
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: all
          custom_payload: |
            {
              Content: `Please review on https://github.com/hitendran/universe-automation/issues/${{ env.ISSUE_NUMBER }}`
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
          PR_NUMBER: ${{ github.event.number }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
