# This is a basic workflow to help you get started with Actions

name: Slack Notification Demo

# Controls when the action will run. 
on: [pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      - run: echo ::set-env name=pull_number::$(jq — raw-output .pull_request.number $GITHUB_EVENT_PATH)
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: ‘Please review on https://github.com/hitendran/universe-automation/pull/${{ env.pull_number}}’
          SLACK_TITLE: ‘Pull request’
