# This is a basic workflow to help you get started with Actions
name: Release Slack Notification

# Controls when the action will run. 
on:
  release:
    types: [published]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Release Slack Notification
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: all
          custom_payload: |
            {
              Type: `${{ env.TAG_NAME }}`,
              Content: `https://github.com/hitendran/universe-automation/tag/${{ env.TAG_NAME }}`
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
          TAG_NAME: ${{ env.RELEASE_VERSION }}
