# This is a basic workflow to help you get started with Actions

name: Slack Notification Demo

# Controls when the action will run. 
on:
  # Triggers the workflow on published release
  release:
    types: published

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      - uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: all
          custom_payload: |
            {
              Content: `*Type:*\n${process.env.AS_EVENT_NAME}`
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
