# This is a basic workflow to help you get started with Actions

name: Slack Notification Demo

# Controls when the action will run. 
on:
  # Triggers the workflow on published release
  release:
    types: published

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      - uses: 8398a7/action-slack@v3
        with:
          status: custom
          custom_payload: |
            {
              Content: "{\r\n                  \"text\": \"I am a test message\",\r\n                  \"attachments\": [\r\n                      {\r\n                          \"text\": \"And here\u2019s an attachment!\"\r\n                      }\r\n                  ]\r\n              }"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
