# This is a basic workflow to help you get started with Actions
name: Slack Notifications Workflow

# Controls when the action will run. 
on: 
  issues:
    types: [opened]
  issue_comment:
    types: [created]
  pull_request:
    types: [opened]
  release:
    types: [published]
   
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  slackNotification:
    name: Slack Notifications Job
    runs-on: ubuntu-latest
    steps:
      - name: Issue Slack Notification
        if: ${{ github.event.issue }}
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: all
          custom_payload: |
            {
              Type: 'Issue',
              Content: `https://github.com/hitendran/universe-automation/issues/${{ env.ISSUE_NUMBER }}`
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
      - name: PR Slack Notification
        if: ${{ github.event.pull_request }}
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: all
          custom_payload: |
            {
              Type: 'Pull Request',
              Content: `https://github.com/hitendran/universe-automation/pull/${{ env.PR_NUMBER }}`
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
          PR_NUMBER: ${{ github.event.number }}
      - name: Set env
        if: ${{ github.ref }}
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Release Slack Notification
        if: ${{ github.ref }}
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: all
          custom_payload: |
            {
              Version: `${{ env.TAG_NAME }}`,
              Content: `https://github.com/hitendran/universe-automation/releases/tag/${{ env.TAG_NAME }}`
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_RELEASE_WEBHOOK }}
          TAG_NAME: ${{ env.RELEASE_VERSION }}
